[[main]]
none = "none"

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "mYq9xpHXsp"
weight = 1

[[main]]
name = "About"
pageRef = "about"
identifier = "nwCdSJ5xLy"
weight = 4

[[main]]
name = "Topics"
pageRef = "topics"
identifier = "lgpFikM3IB"
weight = 3

[[main]]
name = "Tags"
pageRef = "tags"
identifier = "Ku9X7lx0qn"
weight = 2

[[main]]
name = "Reviews"
pageRef = "review"
identifier = "9ohXVux6k0"
weight = 9_999

[[footer]]
none = "none"
